controller:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  left_front_wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheelfl2frame
    pid: { p: 10.0, i: 0.1, d: 0.01 }
  left_back_wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheelbl2frame
    pid: { p: 10.0, i: 0.1, d: 0.01 }
  right_front_wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheelfr2frame
    pid: { p: 10.0, i: 0.1, d: 0.01 }
  right_back_wheel_controller:
    type: effort_controllers/JointEffortController
    joint: wheelbr2frame
    pid: { p: 10.0, i: 0.1, d: 0.01 }
