repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml

  - repo: local
    hooks:
      - id: my-example
        name: My  hook
        entry: .git/hooks/pre-commit
        language: script
        types: [file]
        files: \.(cpp|cxx|h|hpp)$