joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

diff_drive_controller:
  type: diff_drive_controller/DiffDriveController
  left_wheel: ['left_front_wheel_joint','left_back_wheel_joint']
  right_wheel: ['right_front_wheel_joint','right_back_wheel_joint']
  pose_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]
  twist_covariance_diagonal: [ 0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0 ]

gazebo_ros_control:
  pid_gains:
    left_front_wheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    left_back_wheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    right_front_wheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    right_back_wheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
