rm_hw:
  bus:
    - can0
    - can1
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  # Configurations of the actuators
  actuators:
    rotation_joint_motor:
      bus: can0
      id: 0x201
      type: rm_2006
      lp_cutoff_frequency: 30